name: Manual run performance test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  manual-run-performance-test:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/uat'
    strategy:
      matrix:
        environment: [uat]

    name: "manual-run-performance-test"
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Run k6 local test
        uses: grafana/k6-action@e4714b734f2b0afaabeb7b4a69142745548ab9ec # v0.3.1
        env:
            APPLICATION_BASE_URL: ${{ vars.APPLICATION_BASE_URL }}
            APPLICATION_BASE_PATH: ${{ vars.APPLICATION_BASE_PATH }}
            COGNITO_BASE_URL: ${{ vars.COGNITO_BASE_URL }}
            COGNITO_CLIENT_ID:  ${{ secrets.COGNITO_CLIENT_ID }}
            COGNITO_CLIENT_SECRET:  ${{ secrets.COGNITO_CLIENT_SECRET }}
        with:
          filename: performance_test/run_performance_tests.js
          
      - name: Upload performance test file
        if: always()
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: performance-report
          path: performance_summary.html
